name: "Safety SARIF Converter"
description: "Converts Safety JSON output to SARIF format"
inputs:
  input_file:
    description: "Input JSON file from Safety"
    required: true
  output_file:
    description: "Output SARIF file"
    required: true
  manifest:
    description: "Path to manifest file"
    required: true
  tool:
    description: "Tool name (e.g., safety)"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        python3 converter.py \
          --input ${{ inputs.input_file }} \
          --output ${{ inputs.output_file }} \
          --manifest ${{ inputs.manifest }} \
          --tool ${{ inputs.tool }}
      shell: bash
